version: 2.1
executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/node:12

commands:
  setup_yarn:
    description: "Setup yarn with cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    executor: default
    steps:
      - checkout
      - setup_yarn
      - run: mkdir -p /tmp/workspace
      - run:
          command: yarn test --runInBand --coverage --coverageDirectory=/tmp/workspace/coverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "/tmp/reports/junit/js-test-results.xml"
      - store_test_results:
          path: /tmp/reports
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - coverage

  build_storybook:
    executor: default
    steps:
      - checkout
      - setup_yarn
      - run: mkdir -p /tmp/workspace
      - run: yarn build-storybook -o /tmp/workspace/storybook -s static
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - storybook

  danger:
    executor: default
    steps:
      - checkout
      - setup_yarn
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/coverage
      - store_artifacts:
          path: /tmp/workspace/storybook
      - run:
          name: Run DangerCI
          command: yarn danger ci -v -d .circleci/danger/dangerfile.ts

workflows:
  build:
    jobs:
      - test
      - build_storybook
      - danger:
          requires:
            - test
            - build_storybook
