version: 2.1
executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/node:12

commands:
  setup_yarn:
    description: "Setup yarn with cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  test:
    executor: default
    steps:
      - checkout
      - setup_yarn
      - run:
          command: yarn test --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "/tmp/reports/junit/js-test-results.xml"
      - store_test_results:
          path: /tmp/reports

  build_storybook:
    executor: default
    steps:
      - checkout
      - setup_yarn
      - run: yarn build-storybook -o /tmp/storybook -s static
      - store_artifacts:
          path: /tmp/storybook
      - run:
          name: Run DangerCI
          command: yarn danger ci -v -d .circleci/danger/dangerfile.ts

workflows:
  build_and_test:
    jobs:
      - test
      - build_storybook
